/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { Dropdown, User, css, Avatar } from "@nextui-org/react";
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=' relative bg-zinc-600 h-full w-full'>
      <Head>
        <title>Wildy | My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className='w-full h-screen lg:flex lg:justify-center'>
          <img src="/me.png" className='w-full h-screen lg:w-max' />
        </div>
        <div className={`${styles.none} ${styles.avatar}`}>
            <div className='flex items-center'>
              <Avatar 
              src="https://i.postimg.cc/28Vftr6V/me.jpg"
              size= "lg"
              zoomed
             />
              <div className='ml-2'>Wildy Johanes Simanjuntak</div>
            </div>
            <div className='flex'>
              <div className='mx-2'>Contact</div>
              <div className='mx-2'>Github</div>
              <div className='mx-2'>Linkedin</div>
            </div>
        </div>
        <div className='absolute top-0 w-screen border-b-2 border-zinc-500 top-0 lg:hidden'>
        <Dropdown placement="bottom-left">
          <Dropdown.Trigger>
            <User
              as="button"
              size="lg"
              color='default'
              name="Wildy Johanes Simanjuntak"
              description="@jo.14m"
              src="https://i.postimg.cc/28Vftr6V/me.jpg"
              zoomed
            />
          </Dropdown.Trigger>
          <Dropdown.Menu aria-label="User Actions">
            <Dropdown.Item >Contact</Dropdown.Item>
            <Dropdown.Item >Github</Dropdown.Item>
            <Dropdown.Item >Linkedin</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
    </div>
    <div className='absolute top-20 w-full'>
      <p className='text-center text-2xl text-slate-300 font-sans lg:text-5xl'>Web Developer</p>
      <p className='text-center text-normal text-slate-300 font-sans mt-4 lg:text-3xl lg:mx-20'>
          I graduated from Batam State Polytechnic majoring in Informatics
          Engineering with a 3.8 GPA in 2023.
          I had an internship at Labtech International Ltd for 8 months as a
          fullstack developer and worked as a production employee from July 2021
          to July 2022. I am an expert in ExpressJs, NuxtJs, Tailwind, Php, Mysql.
          My hobby is reading books.
      </p>
    </div>
      </main>
    </div>
  )
}
